---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/tours":
    get:
      summary: Retrieves Tours
      tags:
      - Tours
      responses:
        '200':
          description: tours found
          content:
            application/json:
              schema:
                type: object
                properties:
                  tours:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        tourName:
                          type: string
                        picture:
                          type: string
                        description:
                          type: string
                        hotel:
                          type: string
                        price:
                          type: number
                        created_at:
                          type: string
                        updated_at:
                          type: string
                required:
                - tours
        '404':
          description: tours not found
  api/v1/tours/{id}:
    get:
      summary: Retrieves a tour
      tags:
      - Tours
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: tour found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  tourName:
                    type: string
                  picture:
                    type: string
                  description:
                    type: string
                  hotel:
                    type: string
                  price:
                    type: number
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - tourName
                - picture
                - description
                - hotel
                - price
                - created_at
                - updated_at
        '404':
          description: tour not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
